### PR TITLE
Added information about promo codes API endpoint.

### PR DESCRIPTION
**Pull request by kovpas**
Not sure if HTML page with example response is necessary.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Hey @kovpas, thanks for your fast pull request. What would you use this URL for? It's not really an API I guess.

**Comment by kovpas** [comment]
Indeed, it's not API (yet, I hope). It's just a static URL, which you can use to generate promo codes (by parsing HTML) for a given app.

**Comment by KrauseFx** [comment]
I'll think about this issue. Have you seen [codes](https://github.com/krausefx/codes) to generate promo codes from the command line?

**Comment by kovpas** [comment]
Yes, I have. However, list of dependencies for such a small utility is way too big :). Recently I was asked to help with fixing promo codes functionality in itc.cli :)
https://github.com/kovpas/itc.cli/tree/archive

**Comment by KrauseFx** [comment]
I agree, there are quite a lot of dependencies right now. Which ones are you concerned about? I guess `poltergeist` with `phantomjs` is the main one, right? 

After I finished the documentation of the API, I want to migrate all tools to only use a HTTP client instead of a web browser.

**Pull request closed without merging**
